const express = require('express');
const PDFDocument = require('pdfkit');
const { v4: uuidv4 } = require('uuid');
const path = require('path');
const fs = require('fs');
const { getDb } = require('../db/schema');
const { auth, requireRole } = require('../middleware/auth');

const router = express.Router();
const INVOICES_DIR = path.join(__dirname, '..', 'invoices');
if (!fs.existsSync(INVOICES_DIR)) fs.mkdirSync(INVOICES_DIR, { recursive: true });

function generateInvoiceNumber() {
  const now = new Date();
  return `INV-${now.getFullYear()}${String(now.getMonth()+1).padStart(2,'0')}-${Math.floor(Math.random()*9000)+1000}`;
}

function generatePDF(invoice, creator, job, brand) {
  return new Promise((resolve, reject) => {
    const filepath = path.join(INVOICES_DIR, `${invoice.invoice_number}.pdf`);
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const stream = fs.createWriteStream(filepath);
    doc.pipe(stream);
    doc.fontSize(28).font('Helvetica-Bold').fillColor('#1a1a2e').text('INVOICE', 50, 50);
    doc.fontSize(12).font('Helvetica').fillColor('#666').text(invoice.invoice_number, 50, 85);
    doc.moveTo(50,110).lineTo(545,110).lineWidth(1).strokeColor('#e0e0e0').stroke();
    doc.fontSize(10).font('Helvetica-Bold').fillColor('#888').text('FROM', 50, 130);
    doc.fontSize(12).font('Helvetica-Bold').fillColor('#1a1a2e').text(creator.name, 50, 148);
    doc.fontSize(10).font('Helvetica').fillColor('#555').text(creator.email, 50, 164);
    doc.fontSize(10).font('Helvetica-Bold').fillColor('#888').text('BILL TO', 300, 130);
    if (brand) {
      doc.fontSize(12).font('Helvetica-Bold').fillColor('#1a1a2e').text(brand.company || brand.name, 300, 148);
      doc.fontSize(10).font('Helvetica').fillColor('#555').text(brand.email, 300, 164);
    }
    doc.fontSize(10).font('Helvetica-Bold').fillColor('#888').text('DATE', 50, 210);
    doc.fontSize(11).font('Helvetica').fillColor('#1a1a2e').text(new Date().toLocaleDateString(), 50, 226);
    if (invoice.due_date) {
      doc.fontSize(10).font('Helvetica-Bold').fillColor('#888').text('DUE DATE', 300, 210);
      doc.fontSize(11).font('Helvetica').fillColor('#1a1a2e').text(new Date(invoice.due_date).toLocaleDateString(), 300, 226);
    }
    doc.roundedRect(50,270,495,36,4).fill('#f8f8f8');
    doc.fontSize(10).font('Helvetica-Bold').fillColor('#888').text('DESCRIPTION',65,282).text('AMOUNT',480,282,{align:'right',width:60});
    doc.fontSize(12).font('Helvetica').fillColor('#1a1a2e').text(job.title,65,320).text(`${invoice.currency} ${Number(invoice.amount).toFixed(2)}`,480,320,{align:'right',width:60});
    doc.moveTo(350,390).lineTo(545,390).lineWidth(1).strokeColor('#e0e0e0').stroke();
    doc.fontSize(11).font('Helvetica-Bold').fillColor('#888').text('TOTAL DUE',350,400);
    doc.fontSize(20).font('Helvetica-Bold').fillColor('#1a1a2e').text(`${invoice.currency} ${Number(invoice.amount).toFixed(2)}`,350,416,{align:'right',width:190});
    if (invoice.notes) { doc.fontSize(10).font('Helvetica-Bold').fillColor('#888').text('NOTES',50,470); doc.fontSize(10).font('Helvetica').fillColor('#555').text(invoice.notes,50,486,{width:495}); }
    doc.fontSize(9).font('Helvetica').fillColor('#aaa').text('Generated by UGC Studio',50,750,{align:'center',width:495});
    doc.end();
    stream.on('finish', () => resolve(filepath));
    stream.on('error', reject);
  });
}

router.get('/', auth, async (req, res) => {
  try {
    const db = getDb();
    const rows = await db.query(`SELECT i.*, j.title as job_title, u.name as brand_name, u.company as brand_company
      FROM invoices i JOIN jobs j ON i.job_id = j.id LEFT JOIN users u ON i.brand_id = u.id
      WHERE i.creator_id = $1 ORDER BY i.created_at DESC`, [req.user.id]);
    res.json(rows);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

router.post('/', auth, requireRole('creator'), async (req, res) => {
  try {
    const db = getDb();
    const { job_id, amount, currency, due_date, notes } = req.body;
    if (!job_id || amount === undefined) return res.status(400).json({ error: 'job_id and amount required' });
    const jobs = await db.query('SELECT * FROM jobs WHERE id = $1 AND creator_id = $2', [job_id, req.user.id]);
    if (!jobs.length) return res.status(404).json({ error: 'Job not found' });
    const job = jobs[0];
    const creators = await db.query('SELECT * FROM users WHERE id = $1', [req.user.id]);
    const creator = creators[0];
    const brands = job.brand_id ? await db.query('SELECT * FROM users WHERE id = $1', [job.brand_id]) : [];
    const brand = brands[0] || null;
    const id = uuidv4();
    const invoice_number = generateInvoiceNumber();
    const share_token = uuidv4().replace(/-/g, '');
    await db.query(`INSERT INTO invoices (id, job_id, creator_id, brand_id, invoice_number, amount, currency, due_date, notes, status, share_token)
      VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,'draft',$10)`,
      [id, job_id, req.user.id, job.brand_id || null, invoice_number, amount, currency || 'AUD', due_date || null, notes || null, share_token]);
    const invRows = await db.query('SELECT * FROM invoices WHERE id = $1', [id]);
    const invoice = invRows[0];
    try {
      const pdfPath = await generatePDF(invoice, creator, job, brand);
      await db.query('UPDATE invoices SET pdf_path = $1 WHERE id = $2', [pdfPath, id]);
    } catch (err) { console.error('PDF failed:', err.message); }
    const final = await db.query('SELECT * FROM invoices WHERE id = $1', [id]);
    res.status(201).json(final[0]);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

router.put('/:id', auth, requireRole('creator'), async (req, res) => {
  try {
    const db = getDb();
    const rows = await db.query('SELECT * FROM invoices WHERE id = $1 AND creator_id = $2', [req.params.id, req.user.id]);
    if (!rows.length) return res.status(404).json({ error: 'Not found' });
    if (rows[0].status !== 'draft') return res.status(400).json({ error: 'Only draft invoices can be edited' });
    const { amount, currency, due_date, notes } = req.body;
    const f = []; const v = [];
    if (amount !== undefined) { f.push(`amount = $${v.length+1}`); v.push(amount); }
    if (currency) { f.push(`currency = $${v.length+1}`); v.push(currency); }
    if (due_date !== undefined) { f.push(`due_date = $${v.length+1}`); v.push(due_date); }
    if (notes !== undefined) { f.push(`notes = $${v.length+1}`); v.push(notes); }
    if (f.length) { v.push(req.params.id); await db.query(`UPDATE invoices SET ${f.join(', ')} WHERE id = $${v.length}`, v); }
    const updated = (await db.query('SELECT * FROM invoices WHERE id = $1', [req.params.id]))[0];
    const job = (await db.query('SELECT * FROM jobs WHERE id = $1', [updated.job_id]))[0];
    const creator = (await db.query('SELECT * FROM users WHERE id = $1', [req.user.id]))[0];
    const brand = updated.brand_id ? (await db.query('SELECT * FROM users WHERE id = $1', [updated.brand_id]))[0] : null;
    try { const p = await generatePDF(updated, creator, job, brand); await db.query('UPDATE invoices SET pdf_path = $1 WHERE id = $2', [p, req.params.id]); } catch(e) {}
    res.json((await db.query('SELECT * FROM invoices WHERE id = $1', [req.params.id]))[0]);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

router.put('/:id/send', auth, async (req, res) => {
  try {
    const db = getDb();
    const rows = await db.query('SELECT * FROM invoices WHERE id = $1 AND creator_id = $2', [req.params.id, req.user.id]);
    if (!rows.length) return res.status(404).json({ error: 'Not found' });
    await db.query("UPDATE invoices SET status = 'sent' WHERE id = $1", [req.params.id]);
    await db.query('UPDATE jobs SET invoice_sent = 1 WHERE id = $1', [rows[0].job_id]);
    const updated = (await db.query('SELECT * FROM invoices WHERE id = $1', [req.params.id]))[0];
    const shareLink = `${req.headers.origin || process.env.FRONTEND_URL}/invoice/${updated.share_token}`;
    res.json({ ...updated, shareLink });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

router.put('/:id/paid', auth, async (req, res) => {
  try {
    const db = getDb();
    const rows = await db.query('SELECT * FROM invoices WHERE id = $1 AND creator_id = $2', [req.params.id, req.user.id]);
    if (!rows.length) return res.status(404).json({ error: 'Not found' });
    await db.query("UPDATE invoices SET status = 'paid', paid_at = NOW() WHERE id = $1", [req.params.id]);
    await db.query('UPDATE jobs SET invoice_paid = 1 WHERE id = $1', [rows[0].job_id]);
    res.json((await db.query('SELECT * FROM invoices WHERE id = $1', [req.params.id]))[0]);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

router.get('/share/:token', async (req, res) => {
  try {
    const db = getDb();
    const rows = await db.query('SELECT * FROM invoices WHERE share_token = $1', [req.params.token]);
    if (!rows.length) return res.status(404).json({ error: 'Invoice not found' });
    const inv = rows[0];
    const job = (await db.query('SELECT title, description FROM jobs WHERE id = $1', [inv.job_id]))[0];
    const creator = (await db.query('SELECT name, email FROM users WHERE id = $1', [inv.creator_id]))[0];
    const brand = inv.brand_id ? (await db.query('SELECT name, email, company FROM users WHERE id = $1', [inv.brand_id]))[0] : null;
    res.json({ invoice: inv, job, creator, brand });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

router.get('/:id/pdf', auth, async (req, res) => {
  try {
    const db = getDb();
    const rows = await db.query('SELECT * FROM invoices WHERE id = $1 AND (creator_id = $2 OR brand_id = $2)', [req.params.id, req.user.id]);
    if (!rows.length) return res.status(404).json({ error: 'Not found' });
    const inv = rows[0];
    if (!inv.pdf_path || !fs.existsSync(inv.pdf_path)) return res.status(404).json({ error: 'PDF not found' });
    res.setHeader('Content-Disposition', `attachment; filename="${inv.invoice_number}.pdf"`);
    res.setHeader('Content-Type', 'application/pdf');
    res.sendFile(inv.pdf_path);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

module.exports = router;
